### ISSUE TITLE
Merge cfg-if into std?

### ISSUE THREAD

**Issue by CuriouslyCurious** [rust-lang/cfg-if#76]
Seeing as search engines are useless for searching for if this has been answered before I'll ask the question directly here. I apologize if it has been answered elsewhere.

crates.io (total): 
![image](https://github.com/rust-lang/cfg-if/assets/10660675/7c83b956-e34a-4003-b849-3b30e39a6de3)

lib.rs (monthly): 
![image](https://github.com/rust-lang/cfg-if/assets/10660675/7014bfd2-96ec-41cf-bda6-762e05409822)

This crate is being used by an **absurd** amount of users and according to lib.rs `>68 000` crates. Which states quite clearly that `cfg-if` is sorely wanted by Rust users. This crate is also very simple only supplying a single macro that is below a hundred lines of code. 

There is thus a quite obvious question to ask: Why is this not part of the standard library? Why is it instead maintained as a separate crate by the Rust team?

I'd love to see this as part of the standard library as it'd be one less dependency one has to worry if it is going to be `xz`'ed in the dependency tree or not.

**Comment by ChrisDenton** [comment]
See https://github.com/rust-lang/rust/issues/115585

**Comment by CuriouslyCurious** [comment]
Thank you. <3

My searching definitely failed me.  I'll close then.

Hopefully it'll be implemented soon.
