### ISSUE TITLE
error: could not compile `cfg-if` (lib) due to 1 previous error  for mipsel-unknown-linux-musl

### ISSUE THREAD

**Issue by peterwillcn** [rust-lang/cfg-if#80]
https://github.com/peterwillcn/shadowsocks-rust-mips/actions/runs/10281532851/job/28451288168
 ```  
Compiling autocfg v1.3.0
 Compiling cfg-if v1.0.0
error[E0463]: can't find crate for `core`
  |
  = note: the `mipsel-unknown-linux-musl` target may not be installed
  = help: consider downloading the target with `rustup target add mipsel-unknown-linux-musl`

   Compiling typenum v1.17.0
For more information about this error, try `rustc --explain E0463`.
error: could not compile `libc` (lib) due to 1 previous error
warning: build failed, waiting for other jobs to finish...
error: could not compile `cfg-if` (lib) due to 1 previous error
[cross] warning: rust-std is not available for mipsel-unknown-linux-musl
[cross] note: you may need to build components for the target via `-Z build-std=<components>` or in your cross configuration specify `target.mipsel-unknown-linux-musl.build-std`
              the available components are core, std, alloc, and proc_macro
```

**Comment by tgross35** [comment]
This shouldn't be specific to cfg-if, probably just the first thing to fail.

`mipsel-unknown-linux-musl` is not supplied by rustup (see it has no artifacts on the tier 3 list here https://rust-lang.github.io/rustup-components-history/) so `rustup target add ...` won't work (like it suggests). This means you need to use the nightly-only [`build-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) (also suggested).

Was this previously working? You may want to bring it up with `cross`.

**Comment by tgross35** [comment]
Going to close this since it isn't a `cfg-if` problem, feel free to continue discussion here.

**Comment by peterwillcn** [comment]
> Going to close this since it isn't a `cfg-if` problem, feel free to continue discussion here.

Thank you for the information!
